version: 2

formats:
  - pdf
  - epub

python:
  install:
    -
      method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: true
