name: Release

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      -
        name: Install build dependencies
        run: python -m pip install -U .[dev]
      -
        name: Build
        run: python -m build .
      -
        name: Publish
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
